import Head from 'next/head';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <link rel='icon' href='./favicon.ico' />
        <title>My Portfolio</title>
      </Head>
      <html lang='en'>
        <body className={inter.className}>{children}</body>
      </html>
    </>
  );
}
